DDS flavors
opentelekomcloud/python-otcextensions pull request #200
Opened 2021-06-28 14:59 UTC by anton-sidelnikov

2021-06-29 13:09 UTC, lego963 requested changes

2021-06-29 13:09 UTC, lego963 commented on otcextensions/sdk/dds/v3/_proxy.py
> +        """List flavors of all DB instances specifications  in specified region
`specifications  in`
remove please 1 space

2021-06-29 13:09 UTC, lego963 commented on otcextensions/sdk/dds/v3/_proxy.py
> +        :rtype: :class:`~otcextensions.sdk.rds_os.v1.flavor.Flavor`
is it rdsv1?

2021-06-29 15:25 UTC, lego963 approved these changes

2021-06-29 16:31 UTC, gtema approved these changes

2021-06-30 07:39 UTC, anton-sidelnikov commented
regate

2021-06-30 07:51 UTC, merged