Elb v3 next resources
opentelekomcloud/python-otcextensions pull request #217
Opened 2021-07-20 14:59 UTC by anton-sidelnikov

- [x] pool
- [x] member
- [x] health_monitor
- [x] l7 policy
- [x] l7 rule
- [x] proxy unit tests

2021-07-23 15:53 UTC, gtema approved these changes, later dismissed
Not really going very deep shortly before vacation.
Maybe you should look at approach with func tests in https://github.com/opentelekomcloud-infra/octavia-proxy/pull/36 (a very general setup/teardown for network). No problem with changing it in the followup

2021-07-26 08:20 UTC, lego963 requested changes

2021-07-26 08:20 UTC, lego963 commented on otcextensions/sdk/vlb/v3/_proxy.py
> +            :class:`~otcextensions.sdk.dds.v3.flavor.Flavor`.
dds flavor?

2021-07-26 08:20 UTC, lego963 commented on otcextensions/sdk/vlb/v3/member.py
> +    weight = resource.Body('weight')
should weight be `int`?

2021-07-26 14:33 UTC, anton-sidelnikov commented on otcextensions/sdk/vlb/v3/member.py
> +    weight = resource.Body('weight')
fixed

2021-07-26 14:33 UTC, anton-sidelnikov commented on otcextensions/sdk/vlb/v3/_proxy.py
> +            :class:`~otcextensions.sdk.dds.v3.flavor.Flavor`.
fixed

2021-07-26 14:37 UTC, lego963 approved these changes

2021-07-26 15:14 UTC, merged