RDS v3 SDK feature extension
opentelekomcloud/python-otcextensions pull request #235
Opened 2021-10-12 11:41 UTC by ameszi

The following RDS v3 API functionalities have been added to the SDK module:
- Instance actions: restart, change storage size, change flavour
- Tag actions: addition and deletion of instance tags

2021-10-12 11:55 UTC, gtema requested changes
Looks already great. There are however few issues:
- you added methods implementation for the resource but not updated the proxy which defines the interface for those (https://github.com/opentelekomcloud/python-otcextensions/blob/master/otcextensions/sdk/rds/v3/_proxy.py). Surely also tests for the proxy need to be added
- we need to have unittest for every function of the resource that we are adding (https://github.com/opentelekomcloud/python-otcextensions/blob/master/otcextensions/tests/unit/sdk/rds/v3/test_instance.py)
- correspondingly documentation for the new functions is missing as well as desired release note (https://github.com/opentelekomcloud/python-otcextensions/blob/master/doc/source/sdk/resources/rds/v3/instance.rst, https://github.com/opentelekomcloud/python-otcextensions/blob/master/doc/source/sdk/proxies/rds_v3.rst and https://github.com/opentelekomcloud/python-otcextensions/tree/master/releasenotes/notes.

I know this is a lot, but we can manage it ;-)

2021-10-13 10:14 UTC, anton-sidelnikov commented on otcextensions/sdk/rds/v3/_proxy.py
> +        """Chage the instance's flavor.
Change

2021-10-13 10:15 UTC, anton-sidelnikov commented on otcextensions/sdk/rds/v3/_proxy.py
> +            :type session: :class:`~keystoneauth1.adapter.Adapter`
not used

2021-10-14 09:03 UTC, ameszi commented on otcextensions/sdk/rds/v3/_proxy.py
> +        """Chage the instance's flavor.
Fixed.

2021-10-14 09:05 UTC, ameszi commented on otcextensions/sdk/rds/v3/_proxy.py
> +            :type session: :class:`~keystoneauth1.adapter.Adapter`
Fixed.

2021-10-21 08:40 UTC, anton-sidelnikov requested changes

2021-10-21 08:40 UTC, anton-sidelnikov commented on releasenotes/notes/add-rds-v3-operations-8bb9237548466010.yaml
> +    Add RDS v3 SDK support for the following instance operations: restart, resize volume, change flavor, query logs, add/remove tag.
endline missing, all other things are good

2021-10-21 09:22 UTC, ameszi commented on releasenotes/notes/add-rds-v3-operations-8bb9237548466010.yaml
> +    Add RDS v3 SDK support for the following instance operations: restart, resize volume, change flavor, query logs, add/remove tag.
Fixed.

2021-10-21 09:36 UTC, anton-sidelnikov approved these changes

2021-10-21 13:06 UTC, gtema approved these changes

2021-10-21 13:06 UTC, gtema commented on otcextensions/sdk/rds/v3/_proxy.py
> +        if bool(start_date) ^ bool(end_date):
cool

2021-10-21 13:26 UTC, merged