tags for elbv2
opentelekomcloud/python-otcextensions pull request #238
Opened 2021-10-13 16:33 UTC by anton-sidelnikov

#236

2021-10-15 11:00 UTC, vladimirvshivkov submitted a review, later dismissed

2021-10-15 11:06 UTC, outcatcher submitted a review, later dismissed

2021-10-15 11:11 UTC, lego963 submitted a review, later dismissed

2021-10-15 12:20 UTC, irina-pereiaslavskaia submitted a review, later dismissed

2021-10-15 13:11 UTC, gtema requested changes
request for clarification. If there are real reasons we can accept it this way

2021-10-15 13:11 UTC, gtema commented on otcextensions/sdk/elb/v2/listener_tag.py
> +                session.get_project_id() + uri,
actually you should be able to set base_path in the proxy to use desired URL and then you do not need to override the function

2021-10-15 13:11 UTC, gtema commented on otcextensions/sdk/elb/v2/load_balancer_tag.py
> +                session.get_project_id() + uri,
same would be valid here

2021-10-15 13:11 UTC, gtema commented on otcextensions/sdk/elb/v2/_proxy.py
> +        return self._list(_lb_tag.Tag, loadbalancer_id=lb_obj.id, **query)
here you can override base_path for the resource

2021-10-15 13:11 UTC, gtema commented on otcextensions/sdk/elb/v2/_proxy.py
> +             when the tag does not exist.
if you do another change - please remove one leading space to fix the identation

2021-10-15 13:11 UTC, gtema commented on otcextensions/sdk/elb/v2/listener_tag.py
> +            'tag': self._prepare_request_body(patch, prepend_key)
isn't that what can be achieved by setting "resource_key: tag" on the class? Then also this function is not really necessary

2021-10-15 14:12 UTC, anton-sidelnikov commented on otcextensions/sdk/elb/v2/_proxy.py
> +        return self._list(_lb_tag.Tag, loadbalancer_id=lb_obj.id, **query)
but in delete i can't pass path

2021-10-15 14:31 UTC, anton-sidelnikov commented on otcextensions/sdk/elb/v2/listener_tag.py
> +            'tag': self._prepare_request_body(patch, prepend_key)
yes, true

2021-10-15 14:32 UTC, anton-sidelnikov commented on otcextensions/sdk/elb/v2/_proxy.py
> +             when the tag does not exist.
ok

2021-10-15 14:34 UTC, anton-sidelnikov commented on otcextensions/sdk/elb/v2/listener_tag.py
> +                session.get_project_id() + uri,
ok, i just figured out how not to override _find, but _prepare_request still need for delete

2021-10-18 10:36 UTC, gtema requested changes

2021-10-18 10:36 UTC, gtema commented on otcextensions/sdk/elb/v2/listener_tag.py
> +    resources_key = 'tags'
I would put all of this into _base_tag letting only override of the base_path here

2021-10-18 10:36 UTC, gtema commented on otcextensions/sdk/elb/v2/_base_tag.py
> +    def _raw_delete(self, session, **kwargs):
I guess for the case of having separate base class it is more reasonable to override prepare_request here. In this case you do not need to override base_path in every proxy call. It was bad to have same base function in multiple tag classes, but since it now only a single base class - it should be more clear

2021-10-18 10:36 UTC, gtema commented on otcextensions/sdk/elb/v2/_proxy.py
> +             when the tag does not exist.
you still have one empty space in front here

2021-10-18 11:58 UTC, anton-sidelnikov commented on otcextensions/sdk/elb/v2/_base_tag.py
> +    def _raw_delete(self, session, **kwargs):
but after that i still need to override base_path in a list call, is it ok?

2021-10-18 14:06 UTC, gtema approved these changes

2021-10-19 08:10 UTC, anton-sidelnikov commented
recheck

2021-10-19 08:56 UTC, gtema commented
regate

2021-10-19 16:40 UTC, merged