CSS cluster query parameters
opentelekomcloud/python-otcextensions pull request #240
Opened 2021-10-15 13:10 UTC by YustinaKvr

1) add query mapping
2) add query for clusters method

Depends-On: https://github.com/opentelekomcloud-infra/otc-zuul-jobs/pull/87

2021-10-18 10:46 UTC, anton-sidelnikov submitted a review, later dismissed

2021-10-19 16:20 UTC, gtema requested changes
Besides pep warning please update unit test to check supported query mapping (i.e. like in https://github.com/opentelekomcloud/python-otcextensions/blob/master/otcextensions/tests/unit/sdk/rds/v3/test_flavor.py#L38)

2021-10-20 09:44 UTC, anton-sidelnikov submitted a review, later dismissed

2021-10-20 14:41 UTC, anton-sidelnikov approved these changes

2021-10-21 10:58 UTC, gtema approved these changes

2021-10-21 11:18 UTC, merged