Dcaas virtual gateway
opentelekomcloud/python-otcextensions pull request #264
Opened 2022-01-25 22:54 UTC by Polina-Gubina

Dcaas virtual gateway

2022-01-28 08:35 UTC, enrrou approved these changes, later dismissed

2022-01-28 10:06 UTC, anton-sidelnikov requested changes

2022-01-28 10:06 UTC, anton-sidelnikov commented on otcextensions/sdk/dcaas/v2/virtual_gateway.py
> +    # Properties
project_id should be here

2022-01-28 10:06 UTC, anton-sidelnikov commented on otcextensions/sdk/dcaas/v2/virtual_gateway.py
> +    # Properties
and ipsec_bandwidth

2022-01-28 10:06 UTC, anton-sidelnikov commented on releasenotes/notes/dcaas-virtual-gateway-936f572b937b9382.yaml
> +---
add exact points that you added

2022-01-31 08:43 UTC, anton-sidelnikov approved these changes

2022-02-01 08:41 UTC, enrrou approved these changes

2022-02-01 12:46 UTC, merged