Dcs service specification
opentelekomcloud/python-otcextensions pull request #270
Opened 2022-02-08 09:49 UTC by irina-pereiaslavskaia

New resource DCS Service Specification.

2022-02-08 17:22 UTC, enrrou submitted a review, later dismissed

2022-02-09 10:24 UTC, anton-sidelnikov requested changes
Please update the docs for dcs according your changes

2022-02-10 15:06 UTC, anton-sidelnikov submitted a review, later dismissed

2022-02-10 15:12 UTC, vladimirvshivkov submitted a review, later dismissed

2022-02-10 15:35 UTC, enrrou approved these changes, later dismissed

2022-02-14 06:15 UTC, enrrou approved these changes

2022-02-14 08:36 UTC, anton-sidelnikov approved these changes

2022-02-14 09:11 UTC, merged