Dcs availability zones
opentelekomcloud/python-otcextensions pull request #273
Opened 2022-02-14 12:46 UTC by irina-pereiaslavskaia

New DCS AZ resource with tests and docs

2022-02-14 16:26 UTC, enrrou approved these changes

2022-02-14 16:26 UTC, enrrou commented on otcextensions/sdk/dcs/v1/_proxy.py
> +                `~otcextensions.sdk.dcs.v1.availability_zone.AvailabilityZone`
I'm wondering how you managed to fit the line.

2022-02-15 08:04 UTC, SebastianGode approved these changes

2022-02-15 14:09 UTC, anton-sidelnikov requested changes

2022-02-15 14:09 UTC, anton-sidelnikov commented on otcextensions/sdk/dcs/v1/availability_zone.py
> +    resources_key = 'available_zones'
i think better to keep common name availability_zones

2022-02-15 14:09 UTC, anton-sidelnikov commented on otcextensions/sdk/dcs/v1/availability_zone.py
> +    resources_key = 'available_zones'
check if you can change it

2022-02-16 08:35 UTC, irina-pereiaslavskaia commented on otcextensions/sdk/dcs/v1/availability_zone.py
> +    resources_key = 'available_zones'
'available_zones' returns in content of response that's way I use it

2022-02-16 08:42 UTC, anton-sidelnikov approved these changes

2022-02-16 09:01 UTC, lego963 commented
regate

2022-02-16 09:22 UTC, merged