DCAAS Virtual interface resource implementation
opentelekomcloud/python-otcextensions pull request #275
Opened 2022-02-18 17:56 UTC by Polina-Gubina

DCAAS Virtual interface resource implementation

2022-02-24 08:48 UTC, enrrou requested changes
add tests please

2022-02-25 08:57 UTC, enrrou approved these changes

2022-02-25 11:12 UTC, anton-sidelnikov approved these changes

2022-02-25 11:53 UTC, lego963 approved these changes

2022-03-01 13:32 UTC, merged