fix auto scaling tests
opentelekomcloud/python-otcextensions pull request #306
Opened 2022-08-07 20:57 UTC by Polina-Gubina

fix auto scaling tests

2022-08-24 08:11 UTC, anton-sidelnikov requested changes

2022-08-24 08:11 UTC, anton-sidelnikov commented on otcextensions/tests/functional/sdk/auto_scaling/v1/test_instance.py
> +        self._delete_as_group()
i think we do not need this test, because deleting chack in _deinitialize... method

2022-08-24 08:11 UTC, anton-sidelnikov commented on otcextensions/tests/functional/sdk/auto_scaling/v1/test_instance.py
> +    def test_05_find_as_group(self):
this test should be last in the list

2022-08-26 11:05 UTC, anton-sidelnikov requested changes

2022-08-26 11:05 UTC, anton-sidelnikov commented on .stestr.blacklist.functional
> +otcextensions.tests.functional.sdk.auto_scaling.v1.test_group*
pls remove

2022-08-26 11:05 UTC, anton-sidelnikov commented on otcextensions/tests/functional/sdk/auto_scaling/v1/test_instance.py
> +    def test_01_create_as_group(self):
not create but find

2022-08-26 11:05 UTC, anton-sidelnikov commented on otcextensions/tests/functional/sdk/auto_scaling/v1/test_instance.py
> +        self.assertIsNone(as_group)
empty string after

2022-08-26 11:05 UTC, anton-sidelnikov commented on otcextensions/tests/functional/sdk/auto_scaling/v1/test_instance.py
> +    def test_05_simple_delete_as_group(self):
delete this test

2022-08-26 11:05 UTC, anton-sidelnikov commented on otcextensions/tests/functional/sdk/auto_scaling/v1/test_instance.py
> +        self._deinitialize_as_group_with_instance()
delete network after

2022-08-26 16:54 UTC, Aloento approved these changes

2022-08-26 17:53 UTC, anton-sidelnikov approved these changes

2022-08-26 19:23 UTC, YustinaKvr approved these changes

2022-08-26 19:40 UTC, merged