Add find and update for bandwidth
opentelekomcloud/python-otcextensions pull request #328
Opened 2023-02-07 13:57 UTC by Polina-Gubina

add find and update for bandwidth

2023-02-07 16:55 UTC, anton-sidelnikov requested changes

2023-02-07 16:55 UTC, anton-sidelnikov commented on doc/source/sdk/guides/vpc.rst
> +This interface is used to assign a shared bandwidth.
copy paste

2023-02-07 17:10 UTC, anton-sidelnikov approved these changes, later dismissed

2023-02-08 09:35 UTC, anton-sidelnikov approved these changes

2023-02-08 09:36 UTC, anton-sidelnikov commented
let's merge, everything is fine

2023-02-08 09:38 UTC, vladimirvshivkov approved these changes

2023-02-08 09:56 UTC, merged