Vlb pool and member update
opentelekomcloud/python-otcextensions pull request #351
Opened 2023-08-01 08:50 UTC by Polina-Gubina

2023-08-01 09:12 UTC, anton-sidelnikov requested changes

2023-08-01 09:12 UTC, anton-sidelnikov commented on otcextensions/sdk/vlb/v3/pool.py
> +    #: Specifies the time when a backend server group was created.
please remove any mention of enterprise_project_id

2023-08-01 09:12 UTC, anton-sidelnikov commented on otcextensions/sdk/vpc/v1/bandwidth.py
> +from openstack import exceptions
bandwidth here?

2023-08-02 09:12 UTC, anton-sidelnikov submitted a review, later dismissed

2024-06-03 06:40 UTC, vladimirhasko commented
recheck

2024-10-31 09:20 UTC, closed without merging