Obs s3
opentelekomcloud/python-otcextensions pull request #367
Opened 2023-10-05 10:13 UTC by Polina-Gubina

2023-10-16 14:16 UTC, anton-sidelnikov requested changes
https://pypi.org/project/reno/, pls use this for adding release notes

2023-10-18 13:00 UTC, anton-sidelnikov submitted a review, later dismissed

2023-10-18 13:02 UTC, artem-lifshits approved these changes, later dismissed

2024-02-05 12:04 UTC, artem-lifshits commented
Recheck

2024-02-05 14:54 UTC, artem-lifshits approved these changes

2024-10-31 09:20 UTC, closed without merging