fix linter
opentelekomcloud/python-otcextensions pull request #379
Opened 2023-11-17 10:19 UTC by Polina-Gubina

2023-12-01 09:38 UTC, vladimirvshivkov commented
looks good, but also add at least 1 example, please

2023-12-01 12:54 UTC, anton-sidelnikov submitted a review, later dismissed

2023-12-01 12:58 UTC, vladimirvshivkov submitted a review, later dismissed

2023-12-03 23:56 UTC, vladimirhasko requested changes

2023-12-03 23:56 UTC, vladimirhasko commented on doc/source/sdk/guides/lts.rst
> +This interface is used to ge a list of groups.
get

2023-12-03 23:56 UTC, vladimirhasko commented on examples/lts/delete_log_stream.py
> +attrs = {
why attrs here?

2023-12-12 13:44 UTC, anton-sidelnikov approved these changes

2023-12-13 10:37 UTC, vladimirhasko approved these changes

2023-12-13 10:51 UTC, merged