vpcv1
opentelekomcloud/python-otcextensions pull request #387
Opened 2023-12-04 09:57 UTC by Polina-Gubina

2023-12-04 23:30 UTC, vladimirhasko requested changes

2023-12-04 23:30 UTC, vladimirhasko commented on otcextensions/sdk/vpcv1/v1/bandwidth.py
> +
something like the following is missing:

```
from openstack import proxy


class Proxy(proxy.Proxy):

    skip_discovery = True
```

2023-12-05 19:46 UTC, vladimirhasko requested changes

2023-12-05 19:46 UTC, vladimirhasko commented on otcextensions/sdk/vpcv1/vpc_service.py
> +from otcextensions.sdk.vpc.v1 import _proxy
from otcextensions.sdk.vpcv1.v1 import _proxy

2023-12-29 17:59 UTC, artem-lifshits commented
Recheck

2024-05-31 06:55 UTC, vladimirhasko commented
recheck

2024-06-03 06:40 UTC, vladimirhasko commented
recheck

2024-10-31 09:20 UTC, closed without merging