[Feat.] Missing proxies for er, fg and apig
opentelekomcloud/python-otcextensions pull request #491
Opened 2024-11-14 15:09 UTC by anton-sidelnikov

Added missing proxies for newest services
Closes https://github.com/opentelekomcloud/python-otcextensions/issues/469
Closes https://github.com/opentelekomcloud/python-otcextensions/issues/468
Closes https://github.com/opentelekomcloud/python-otcextensions/issues/450

2024-11-14 17:50 UTC, RusselSand approved these changes, later dismissed

2024-11-15 14:17 UTC, vladimirhasko requested changes

2024-11-15 14:17 UTC, vladimirhasko commented on otcextensions/sdk/apig/apig_service.py
> +            base_service="aomv2",
wrong, aomv2 is not in apig

2024-11-18 09:14 UTC, anton-sidelnikov commented on otcextensions/sdk/apig/apig_service.py
> +            base_service="aomv2",
fixed

2024-11-18 09:31 UTC, vladimirhasko approved these changes

2024-11-18 09:44 UTC, merged