Add query operations for public/target VPC endpoint services
opentelekomcloud/python-otcextensions pull request #492
Opened 2024-11-15 07:27 UTC by wuebbels

Add query operations for public VPC endpoint services and target VPC endpoint service

2024-11-15 12:08 UTC, vineet-pruthi commented
recheck

2024-11-15 14:42 UTC, vineet-pruthi submitted a review, later dismissed

2024-11-18 11:58 UTC, anton-sidelnikov requested changes
any tests? unit or acceptance

2024-11-19 10:15 UTC, vineet-pruthi commented
added unit tests

2024-11-19 14:24 UTC, vineet-pruthi approved these changes

2024-11-19 14:44 UTC, anton-sidelnikov approved these changes

2024-11-19 14:56 UTC, merged