Adding OCR sdk proxy implementation
opentelekomcloud/python-otcextensions pull request #500
Opened 2024-12-11 13:18 UTC by sattila1999

2024-12-11 13:50 UTC, anton-sidelnikov requested changes
please add functional test_service test to check if connection successfully created for ocr

2024-12-13 13:17 UTC, sattila1999 commented
Hi @anton-sidelnikov!

Added sdk functional OCR proxy connection test. We also created a merge request for OCR endpoint entry in service catalog.

2025-01-20 18:08 UTC, anton-sidelnikov approved these changes

2025-01-21 08:55 UTC, anton-sidelnikov commented
Hi @sattila1999, tests failed because: keystoneauth1.exceptions.catalog.EndpointNotFound: public endpoint for ocr service in eu-de region not found

2025-01-23 08:56 UTC, sattila1999 commented
> Hi @sattila1999, tests failed because: keystoneauth1.exceptions.catalog.EndpointNotFound: public endpoint for ocr service in eu-de region not found

Hi @anton-sidelnikov,

thanks for the highlight. We have already created the merge request to add the OCR endpoint entry in service catalog, but it's still awaiting.

2025-01-23 16:51 UTC, vineet-pruthi commented
recheck

2025-01-24 10:07 UTC, anton-sidelnikov approved these changes

2025-01-24 10:18 UTC, merged