First NAT implementation for SDK
opentelekomcloud/python-otcextensions pull request #52
Opened 2019-11-18 15:49 UTC by tischrei

NAT implementation done and tested. Unit / functional testing and doc will follow up asap.

2019-12-06 11:05 UTC, gtema requested changes
test_proxy is empty, what is a bit too few ;-)

2019-12-06 11:05 UTC, gtema commented on otcextensions/sdk/nat/v2/_proxy.py
> +        :param dict attrs: Keyword arguments which will be used to create
create!=delete, argument name id is not ok, since we might want to pass the gateway object itself

2019-12-06 11:05 UTC, gtema commented on otcextensions/sdk/nat/v2/_proxy.py
> +    def delete_snat_rule(self, id):
here also not only id, but snat_rule itself should be supported

2019-12-06 11:05 UTC, gtema commented on otcextensions/sdk/nat/v2/_proxy.py
> +        :param dict attrs: Keyword arguments which will be used to create
create!=delete

2019-12-06 11:05 UTC, gtema commented on otcextensions/sdk/nat/v2/_proxy.py
> +    def delete_dnat_rule(self, id):
same here

2019-12-06 11:05 UTC, gtema commented on otcextensions/sdk/nat/v2/dnat.py
> +    tenant_id = resource.Body('tenant_id')
project_id = tenant_id

2019-12-06 11:05 UTC, gtema commented on otcextensions/sdk/nat/v2/gateway.py
> +        'spec', 'status', 'tenant_id'
'project_id', project_id='tenant_id'

2019-12-06 11:05 UTC, gtema commented on otcextensions/sdk/nat/v2/snat.py
> +    tenant_id = resource.Body('tenant_id')
project_id  = tenant_id

2019-12-06 11:05 UTC, gtema commented on otcextensions/sdk/nat/v2/_proxy.py
> +# Gateway
please indent comment

2019-12-06 15:38 UTC, tischrei commented
> test_proxy is empty, what is a bit too few ;-)

Sorry, the test_proxy.py was in branch cloudeye :-D

2019-12-06 15:43 UTC, tischrei commented
all changes are done. Rereview would be apreciated :-D

2019-12-12 11:12 UTC, gtema approved these changes

2019-12-12 11:12 UTC, merged